{
    "name": "SaleS GRG",
    "summary": "Manufacturing For GRG",
    "author": "Emad GRG ",
    "category": "MRP",
    "version": "18.0.0.9",
    "license": "AGPL-3",
    "depends": ['account','sale','stock','sale_management','purchase','stock_account','mrp','hr'],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/partner_constrains.xml",
        'views/account_invoice.xml',
        'views/sale_order.xml',
        'views/purchase_order.xml',
        'views/stock_move_views.xml',
        'views/mrp_request_views.xml',
        'views/mrp_bom.xml',
        # 'views/bank_statement.xml',
        'reports/order_to_mrp.xml',
        'reports/po_cover_head.xml',
        # 'views/price_list.xml',
    ],
    "application": True,
    "installable": True,
    "support": "emad.raafat155@gmail.com",
    'images': ['images/timesheetontask.png'],
}
